name: ManagedShell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        buildconfig: [ Release ]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0
      id: nbgv

    - name: Build
      run: dotnet build -c $env:Config -p:Version=${{ steps.nbgv.outputs.SemVer2 }}
      env:
        Config: ${{ matrix.buildconfig }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ManagedShell nupkg
        path: '**\*.nupkg'
