name: ManagedShell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        buildconfig: [ Release ]
        project: [ src\ManagedShell\ManagedShell.csproj ]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Build
      run: dotnet build $env:Project -c $env:Config
      env:
        Config: ${{ matrix.buildconfig }}
        Project: ${{ matrix.project }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ManagedShell nupkg
        path: '**\*.nupkg'
