name: ManagedShell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        buildconfig: [ Release ]

    runs-on: windows-latest

    env:
      project: src\ManagedShell\ManagedShell.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Build
      run: dotnet build $env:project -c $env:config
      env:
        config: ${{ matrix.buildconfig }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ManagedShell nupkg
        path: '**\*.nupkg'

  publish:
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      id: nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Build and publish to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/ManagedShell/ManagedShell.csproj
        VERSION_STATIC: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true